[0m15:41:30.904235 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016FF5B4C920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016FF6651970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016FF6651EE0>]}


============================== 15:41:30.920244 | 7b33e4f6-fb26-4d86-8e1f-fb650b1633d2 ==============================
[0m15:41:30.920244 [info ] [MainThread]: Running with dbt=1.8.5
[0m15:41:30.921244 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m15:41:30.936741 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/Haroon/.dbt')}
[0m15:41:30.937741 [info ] [MainThread]: Creating dbt configuration folder at 
[0m15:41:52.387527 [debug] [MainThread]: Starter project path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m15:41:52.412805 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:41:52.415806 [info ] [MainThread]: Setting up your profile.
[0m15:42:21.242805 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m15:42:21.243817 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m15:42:21.243817 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m15:54:32.288768 [info ] [MainThread]: Profile data_pipeline written to C:\Users\Haroon\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:54:32.291692 [debug] [MainThread]: Command `dbt init` succeeded at 15:54:32.290693 after 781.49 seconds
[0m15:54:32.291692 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016FF6318E30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016FF70C0710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016FF6029AC0>]}
[0m15:54:32.292692 [debug] [MainThread]: Flushing usage events
[0m15:55:43.652095 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD8C0DEF60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD8C0DEE70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD8C0DEE10>]}


============================== 15:55:43.656107 | 2100b951-d970-498a-b2ac-7a1a41199b36 ==============================
[0m15:55:43.656107 [info ] [MainThread]: Running with dbt=1.8.5
[0m15:55:43.656107 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:55:43.657136 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Haroon\Desktop\databricks_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:55:43.658100 [debug] [MainThread]: Command `dbt run` failed at 15:55:43.658100 after 0.10 seconds
[0m15:55:43.659184 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD8BF01640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD8B5269F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD8B8279E0>]}
[0m15:55:43.659184 [debug] [MainThread]: Flushing usage events
[0m15:57:11.503452 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E16C3E7CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E16B790740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E16B793350>]}


============================== 15:57:11.506464 | 05ffdb8c-5db5-4b83-ac23-853c8c73c34e ==============================
[0m15:57:11.506464 [info ] [MainThread]: Running with dbt=1.8.5
[0m15:57:11.507461 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:57:11.520886 [info ] [MainThread]: dbt version: 1.8.5
[0m15:57:11.520886 [info ] [MainThread]: python version: 3.12.5
[0m15:57:11.521877 [info ] [MainThread]: python path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\python.exe
[0m15:57:11.521877 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m15:57:11.627459 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m15:57:11.628531 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m15:57:11.628531 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m15:57:12.715344 [info ] [MainThread]: Using profiles dir at C:\Users\Haroon\.dbt
[0m15:57:12.715344 [info ] [MainThread]: Using profiles.yml file at C:\Users\Haroon\.dbt\profiles.yml
[0m15:57:12.716303 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Haroon\Desktop\databricks_project\dbt_project.yml
[0m15:57:12.717283 [info ] [MainThread]: adapter type: databricks
[0m15:57:12.717283 [info ] [MainThread]: adapter version: 1.8.5
[0m15:57:12.718303 [info ] [MainThread]: Configuration:
[0m15:57:12.718303 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m15:57:12.719315 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m15:57:12.719315 [info ] [MainThread]: Required dependencies:
[0m15:57:12.720311 [debug] [MainThread]: Executing "git --help"
[0m15:57:12.748872 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m15:57:12.748872 [debug] [MainThread]: STDERR: "b''"
[0m15:57:12.748872 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m15:57:12.749949 [info ] [MainThread]: Connection:
[0m15:57:12.750959 [info ] [MainThread]:   host: https://dbc-409663c5-8ce7.cloud.databricks.com/?autoLogin=true&account_id=92ce8928-27f4-4338-ad43-9a33d6c7bee3&o=118177683434580
[0m15:57:12.751595 [info ] [MainThread]:   http_path: /sql/1.0/warehouses/6f8737e4c7d463da
[0m15:57:12.751595 [info ] [MainThread]:   catalog: samples
[0m15:57:12.752605 [info ] [MainThread]:   schema: tpch
[0m15:57:12.752605 [info ] [MainThread]: Registered adapter: databricks=1.8.5
[0m15:57:12.753611 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2067700047392, session-id=None, name=debug, idle-time=0s, acquire-count=0, language=None, thread-identifier=(2292, 19136), compute-name=) - Creating connection
[0m15:57:12.753611 [debug] [MainThread]: Acquiring new databricks connection 'debug'
[0m15:57:12.754604 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2067700047392, session-id=None, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(2292, 19136), compute-name=) - Acquired connection on thread (2292, 19136), using default compute resource
[0m15:57:12.754604 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2067700047392, session-id=None, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(2292, 19136), compute-name=) - Checking idleness
[0m15:57:12.754604 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2067700047392, session-id=None, name=debug, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(2292, 19136), compute-name=) - Retrieving connection
[0m15:57:12.754604 [debug] [MainThread]: Using databricks connection "debug"
[0m15:57:12.755604 [debug] [MainThread]: On debug: select 1 as id
[0m15:57:12.755604 [debug] [MainThread]: Opening a new connection, currently in state init
[0m15:59:34.415483 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2067700047392, session-id=None, name=debug, idle-time=0.0s, acquire-count=0, language=None, thread-identifier=(2292, 19136), compute-name=) - Released connection
[0m15:59:34.416489 [error] [MainThread]: Encountered an error:

[0m15:59:34.429398 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 406, in debug
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\debug.py", line 150, in run
    connection_status = self.test_connection()
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\debug.py", line 471, in test_connection
    connection_result = self.attempt_connection(self.profile)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\debug.py", line 449, in attempt_connection
    adapter.debug_query()
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\adapters\spark\impl.py", line 508, in debug_query
    self.execute("select 1 as id")
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\adapters\databricks\utils.py", line 78, in wrapper
    return func(*new_args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\adapters\databricks\impl.py", line 230, in execute
    return super().execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\adapters\base\impl.py", line 356, in execute
    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\adapters\databricks\connections.py", line 629, in execute
    _, cursor = self.add_query(sql, auto_begin)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\adapters\databricks\connections.py", line 600, in add_query
    cursor = cast(DatabricksSQLConnectionWrapper, connection.handle).cursor()
                                                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\adapters\contracts\connection.py", line 95, in handle
    self._handle.resolve(self)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\adapters\contracts\connection.py", line 119, in resolve
    return self.opener(connection)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\adapters\databricks\connections.py", line 1080, in open
    return cls.retry_connection(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\adapters\base\connections.py", line 237, in retry_connection
    connection.handle = connect()
                        ^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\adapters\databricks\connections.py", line 1044, in connect
    conn = dbsql.connect(
           ^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\databricks\sql\__init__.py", line 90, in connect
    return Connection(server_hostname, http_path, access_token, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\databricks\sql\client.py", line 233, in __init__
    self._open_session_resp = self.thrift_backend.open_session(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\databricks\sql\thrift_backend.py", line 578, in open_session
    response = self.make_request(self._client.OpenSession, open_session_req)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\databricks\sql\thrift_backend.py", line 495, in make_request
    response_or_error_info = attempt_request(attempt)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\databricks\sql\thrift_backend.py", line 405, in attempt_request
    response = method(request)
               ^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\databricks\sql\thrift_api\TCLIService\TCLIService.py", line 204, in OpenSession
    self.send_OpenSession(req)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\databricks\sql\thrift_api\TCLIService\TCLIService.py", line 213, in send_OpenSession
    self._oprot.trans.flush()
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\databricks\sql\auth\thrift_http_client.py", line 177, in flush
    self.__resp = self.__pool.request(
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\_request_methods.py", line 144, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 944, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 4 more times]
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 942, in urlopen
    retries.sleep(response)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 363, in sleep
    self._sleep_backoff()
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 347, in _sleep_backoff
    time.sleep(backoff)
KeyboardInterrupt

[0m15:59:34.441040 [debug] [MainThread]: Command `dbt debug` failed at 15:59:34.440029 after 143.03 seconds
[0m15:59:34.441040 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m15:59:34.441040 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E16C3E7CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E17EEBCBF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E17EEEAF90>]}
[0m15:59:34.442039 [debug] [MainThread]: Flushing usage events
[0m16:09:38.733118 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F098BFE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F0BEFC800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F0B3869C0>]}


============================== 16:09:38.737131 | 198e121c-5cd4-467e-8473-1ee0cda87cd1 ==============================
[0m16:09:38.737131 [info ] [MainThread]: Running with dbt=1.8.5
[0m16:09:38.738122 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:09:38.738122 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Haroon\Desktop\databricks_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:09:38.739122 [debug] [MainThread]: Command `dbt run` failed at 16:09:38.739122 after 0.08 seconds
[0m16:09:38.739122 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F0C0C6330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F0BF1DAF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F0BFC1070>]}
[0m16:09:38.740129 [debug] [MainThread]: Flushing usage events
[0m16:14:44.398986 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A38B1AEBD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A38CE42450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A38CE41FA0>]}


============================== 16:14:44.401996 | 25380ce9-0667-4fb1-a8f8-415f530faa09 ==============================
[0m16:14:44.401996 [info ] [MainThread]: Running with dbt=1.8.5
[0m16:14:44.402986 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:14:44.402986 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Haroon\Desktop\databricks_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:14:44.403986 [debug] [MainThread]: Command `dbt deps` failed at 16:14:44.403986 after 0.08 seconds
[0m16:14:44.403986 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A38DDBF2F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A38BA09070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A38B1AEBD0>]}
[0m16:14:44.404995 [debug] [MainThread]: Flushing usage events
